default_stages: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: (\.min\.js$|\.svg$)
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
- repo: https://github.com/hoxbro/clean_notebook
  rev: v0.1.10
  hooks:
    - id: clean-notebook
