default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: (\.min\.js$|\.svg$)
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        exclude: \.ipynb
  - repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.17
    hooks:
      - id: clean-notebook
