# -*- coding: utf-8 -*-
import os
import param
import pydata_sphinx_theme

param.parameterized.docstring_signature = False
param.parameterized.docstring_describe_params = False

from nbsite.shared_conf import *  # noqa

if pydata_sphinx_theme.__version__ == '0.16.1':
    # See https://github.com/pydata/pydata-sphinx-theme/issues/2088
    templates_path.append('_static/patch_templates')  # noqa

def patch_autosummary():
    # See https://github.com/sphinx-doc/sphinx/issues/13991
    import sphinx.ext.autosummary


    def patch_get_import_prefixes_from_env(env) -> list[str | None]:
        """Obtain current Python import prefixes (for `import_by_name`)
        from ``document.env``.
        """
        prefixes: list[str | None] = [None]

        currmodule = env.ref_context.get('py:module')
        if currmodule:
            prefixes.insert(0, currmodule)

        # Commenting out this bit to remove the prefix that messes up
        # documenting the rx class that has the rx property.

        # currclass = env.ref_context.get('py:class')
        # if currclass:
        #     if currmodule:
        #         prefixes.insert(0, f'{currmodule}.{currclass}')
        #     else:
        #         prefixes.insert(0, currclass)

        return prefixes

    sphinx.ext.autosummary.get_import_prefixes_from_env = patch_get_import_prefixes_from_env

patch_autosummary()


project = 'param'
authors = 'HoloViz developers'
copyright_years['start_year'] = '2003'  # noqa
copyright = copyright_fmt.format(**copyright_years)  # noqa
description = 'Declarative Python programming using Parameters'

# Useful for SEO on a versioned site
html_baseurl = 'https://d1e86hvd7le0jf.cloudfront.net/en/docs/latest/'

version = release = base_version(param.__version__)  # noqa

nbbuild_cell_timeout = 600

html_static_path += ['_static']  # noqa

html_logo = "_static/logo_horizontal.png"

html_favicon = "_static/favicon.ico"

exclude_patterns = ['governance/**/*.*', 'Promo.ipynb']

html_context.update(  # noqa
    {
        'last_release': f'v{release}',
        'default_mode': 'light',
        # Useful for the edit button
        'github_user': 'holoviz',
        'github_repo': 'param',
        'github_version': 'main',
        'doc_path': 'doc',
    }
)

switcher_version = (
    os.getenv('VERSION') or 'dev'
    if any(pr in param.__version__ for pr in ('a', 'b', 'rc', 'dev'))
    else version
)

html_theme_options = {
    "use_edit_page_button": True,
    "navbar_start": ["navbar-logo", "version-switcher"],
    "github_url": "https://github.com/holoviz/param",
    "icon_links": [
        {
            'name': 'Twitter',
            'url': 'https://twitter.com/holoviz_org',
            'icon': 'fa-brands fa-twitter-square',
        },
        {
            "name": "Discourse",
            "url": "https://discourse.holoviz.org/",
            "icon": "fa-brands fa-discourse",
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/AXRHnJU6sP",
            "icon": "fa-brands fa-discord",
        },
    ],
    "footer_start": [
        "copyright",
        "last-updated",
    ],
    "switcher": {
        "json_url": "https://d1e86hvd7le0jf.cloudfront.net/switcher.json",
        "version_match": switcher_version,
    },
    "show_version_warning_banner": True,
}

extensions += [  # noqa
    'sphinx_copybutton',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosummary',
    'sphinx_remove_toctrees',
    'nbsite.analytics',
]
remove_from_toctrees = ["reference/param/generated/*"]

nbsite_analytics = {
    'goatcounter_holoviz': True,
}

# Skip all prompt characters generated by pygments like >>>
copybutton_exclude = '.linenos, .gp'

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

rediraffe_redirects = {
    # API docs re-org
    'reference/param/parameter_helpers': 'reference/param/parameters',
    'reference/param/parameterized_helpers': 'reference/param/parameterized',
    'reference/param/parameterized_objects': 'reference/param/parameterized',
}

# Override the Sphinx default title that appends `documentation`
html_title = f'{project} v{version}'
# Format of the last updated section in the footer
html_last_updated_fmt = '%Y-%m-%d'

# Without this .txt is appended to the files
html_sourcelink_suffix = ''

myst_heading_anchors = 3
myst_enable_extensions = ["colon_fence"]

napoleon_numpy_docstring = True
