from typing import Any, Optional, overload

class String:
    default: Optional[str]
    def __get__(self, instance: Any, owner: Any) -> Optional[str]: ...
    def __set__(self, instance: Any, value: Optional[str]) -> None: ...
    def __init__(self, default: Optional[str] = ..., doc: Optional[str] = ...) -> None: ...

class ParameterizedMetaclass(type): ...