from typing import Any, Optional

class Number:
    default: float
    def __get__(self, instance: Any, owner: Any) -> float: ...
    def __set__(self, instance: Any, value: float) -> None: ...
    def __init__(self, default: Optional[float] = ..., doc: Optional[str] = ...) -> None: ...

class String:
    default: str
    def __get__(self, instance: Any, owner: Any) -> str: ...
    def __set__(self, instance: Any, value: str) -> None: ...
    def __init__(self, default: Optional[str] = ..., doc: Optional[str] = ...) -> None: ...