name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_suite:
    name: Tox on ${{ matrix.python-version }}, ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ${{ ( github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || ( github.event_name == 'push' && github.ref_type == 'tag' ) ) && fromJSON('["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.9"]') || fromJSON('["3.7", "3.9", "3.11"]') }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "100"
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: env setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch
      - name: run tests
        run: hatch run tests:test
      - uses: codecov/codecov-action@v3
        if: github.event_name == 'push'
